components/teaser/config/routes.rb
Teaser::Engine.routes.draw do
  resources "tease", only: [:new, :create]
  root :to => 'tease#new'
end

components/teaser/app/controllers/teaser/application_controller.rb
module Teaser
  class ApplicationController < ActionController::Base
  end
end

components/teaser/app/controllers/teaser/tease_controller.rb
module Teaser
  class TeaseController < Teaser::ApplicationController

    before_filter :inject_dependencies, only: [:create]

    def new
    end

    def create
      email = params[:new_sign_up_entry].presence
      render text: "Hey! Please call this right... I need a new signUp entry!", status: 400 and return unless email

      if similar_exisiting_entry = @entry_manager.find_by_email(email)
        tries = @event_counter.log("email_signup_entry_#{similar_exisiting_entry.id}", "signup")
        render(
            text: @annoyance_meter.annoyance_adjusted("Hm... Did you already sign up?", tries),
            status: 400) and return
      elsif @entry_manager.create(email)
        render text: "Thanks for signing up!", status: 200
      else
        render text: "Hm... something went seriously wrong.", status: 500
      end
    end

    private

    def inject_dependencies
      @entry_manager = EmailSignup::EntryManager.new
      @annoyance_meter = Annoyance::Meter.new(10)
      @event_counter = EventCounter::Logger.new
    end
  end
end

components/teaser/app/views/layouts/teaser/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
  <title>Teaser</title>
  <%= stylesheet_link_tag "teaser/application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="header">
  <%= content_for :header %>
</div>
<div id="top">
  <%= content_for :top %>
</div>
<a href="https://github.com/shageman/the_next_big_thing">
  <img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png" alt="Fork me on GitHub">
</a>
<div id="center">
  <div id="content">
    <%= yield %>
  </div>
</div>
<div id="footer">
  <%= content_for :footer %>
</div>
</body>
<%= javascript_include_tag "teaser/application" %>
</html>

components/teaser/app/views/teaser/tease/new.html.haml
-content_for :header do
  The Next Big Thing

%p Find nothing out about it right here!

%p Also: sign up to receive our updates

%form
  %input#signup

#results

:javascript
  window.createTeaserUrl = "#{tease_index_url}";